version: "3.7"

services:
  home-assistant:
    image: homeassistant/home-assistant:stable
    container_name: "home-assistant"
    network_mode: host
    restart: unless-stopped
    environment:
      TZ: Asia/Almaty
    volumes:
      - ~/home_assistant/config:/config

